### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ramdgupta** [creativetimofficial/argon-design-system-react#14]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1218:7)
    at noopServiceWorkerMiddleware (/media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/express/lib/router/index.js:317:13)
    at /media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/express/lib/router/index.js:335:12)
    at next (/media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/media/disk1/crashCourse/react/argon-design-system-react-master/node_modules/express/lib/router/layer.js:95:5)

**Comment by einazare** [comment]
This issue was closed due to not enough information. Please read our terms:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-design-system-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

**Comment by mesili** [comment]
Just so you know, if you bump `react-scripts` to 3.4.0 in package.json this error will disappear.

**Comment by JoeEarly** [comment]
Thanks for that @mesili
