### ISSUE TITLE
Build succeeded but getting an error while launching the app

### ISSUE THREAD

**Issue by saleemkhan08** [creativetimofficial/argon-design-system-react#9]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/express/lib/router/index.js:317:13)
    at /Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/saleemkhan/projects/reactjs/PickupNdrop2/node_modules/express/lib/router/layer.js:95:5)

**Comment by einazare** [comment]
Hello there, @saleemkhan08 ,

To solve this issue, please change react-scripts from `3.3.1` to `3.4.0`.
Next time, please use our issue template:
```
<!--
 IMPORTANT: Please use the following link to create a new issue:

  https://www.creative-tim.com/new-issue/argon-design-system-react

**If your issue was not created using the app above, it will be closed immediately.**
-->

<!--
Love Creative Tim? Do you need Angular, React, Vuejs or HTML? You can visit:
👉  https://www.creative-tim.com/bundles
👉  https://www.creative-tim.com
-->
```

Best,
Manu

**Comment by saleemkhan08** [comment]
Thank you so much. It's working now.
